### ISSUE TITLE
Missing header in libsrc/core/memtracer.cpp

### ISSUE THREAD

**Issue by rubenhorn** [NGSolve/netgen#251]
I'm trying to build ngsolve using Intel oneAPI compilers (2024.1.0).  
When compiling `libsrc/core/memtracer.cpp`, I encounter (among similar errors):
```
.../ngsuite/ngsolve-src/external_dependencies/netgen/libsrc/core/memtracer.cpp:58:16: error: no member named 'setw' in namespace 'std'
 58 |     using std::setw;
    |           ~~~~~^

```

This requires the missing header `#include <iomanip>`.

It used to work with GNU 13.2.0, but not GNU 8.5.
(Probably this header was added implicitly.)

**Comment by rubenhorn** [comment]
Resolved by removing hidden GNU 8.5.
